In [1]:
import os, sys

PROJECT_ROOT = '/scratch/jq2uw/derm_vlms'
MEDGEMMA_DIR = os.path.join(PROJECT_ROOT, 'collect_ai_response', 'medgemma')

if MEDGEMMA_DIR not in sys.path:
    sys.path.insert(0, MEDGEMMA_DIR)

os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:128'

import torch
torch.cuda.empty_cache()

# HF token for gated MedGemma model
sys.path.insert(0, PROJECT_ROOT)
from tokens import HF_TOKEN

from utils import load_model, predict_image, parse_label

print('Loading model...')
model, processor = load_model(hf_token=HF_TOKEN)
print('Model loaded.')

/home/jq2uw/.local/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading model...

`torch_dtype` is deprecated! Use `dtype` instead!
Fetching 2 files: 100%|████████████████████████████████████████████████████████████| 2/2 [00:22<00:00, 11.16s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.60s/it]
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

Total params: 4,300,079,472
Model loaded.

In [2]:
import pandas as pd
from pathlib import Path

sys.path.insert(0, PROJECT_ROOT)
from data_utils import prepare_all_lesions

DATA_DIR = os.path.join(PROJECT_ROOT, 'data')
RESULTS_DIR = os.path.join(PROJECT_ROOT, 'results')
IMAGES_DIR = os.path.join(RESULTS_DIR, 'images')
OUT_PATH = os.path.join(RESULTS_DIR, 'medgemma_predictions_all.csv')

df = pd.read_parquet(os.path.join(PROJECT_ROOT, 'data_share', 'midas_share.parquet'))
print(f'Loaded {len(df)} rows')
print(f'y3 distribution:\n{df["y3"].value_counts()}')
print(f'y16 distribution:\n{df["y16"].value_counts()}')

df_all = prepare_all_lesions(df, data_dir=DATA_DIR, output_dir=IMAGES_DIR)
print(f'\nTotal prediction rows: {len(df_all)}')
df_all.head(10)

Loaded 3357 rows
y3 distribution:
y3
malignant    1391
benign       1322
other         644
Name: count, dtype: int64
Sampled 10 lesions (5 per class) -> 30 rows
Classes: {'benign': 15, 'malignant': 15}
Images saved to: /scratch/jq2uw/derm_vlms/results/images

,id,ground_truth,image_mode,image_path,original_image_name,lesion_id
0,1_photo,benign,photo,/scratch/jq2uw/derm_vlms/results/images/1_phot...,s-prd-667118134.jpg,534_left lower leg_no
1,1_dscope,benign,dscope,/scratch/jq2uw/derm_vlms/results/images/1_dsco...,s-prd-667118139.jpg,534_left lower leg_no
2,1_combined,benign,combined,/scratch/jq2uw/derm_vlms/results/images/1_comb...,s-prd-667118134.jpg; s-prd-667118139.jpg,534_left lower leg_no
3,2_photo,benign,photo,/scratch/jq2uw/derm_vlms/results/images/2_phot...,s-prd-505211076.jpg,215_central chest _no
4,2_dscope,benign,dscope,/scratch/jq2uw/derm_vlms/results/images/2_dsco...,s-prd-505211307.jpg,215_central chest _no

In [3]:
from PIL import Image
from tqdm import tqdm

PROMPT = ("You are an expert dermatologist. Please describe using dermatological "
          "terms to describe the appearance of this lesion. "
          "Please give the top 3 diagnoses in your differential.")

CHECKPOINT_EVERY = 10
COL_ORDER = ['id', 'ground_truth', 'y16', 'y16_description', 'image_mode',
             'describe_then_classify', 'image_path', 'original_image_name', 'lesion_id']

# --- Resume logic ---
if os.path.exists(OUT_PATH):
    existing_df = pd.read_csv(OUT_PATH)
    done_ids = set(existing_df['id'].tolist())
    print(f'Resuming: {len(done_ids)} predictions already completed')
else:
    done_ids = set()

pending = df_all[~df_all['id'].isin(done_ids)]
print(f'{len(pending)} predictions remaining out of {len(df_all)} total')

# --- Prediction loop with checkpointing ---
batch = []
lesions_in_batch = set()

for _, row in tqdm(pending.iterrows(), total=len(pending)):
    try:
        image = Image.open(row['image_path']).convert('RGB')
    except Exception as e:
        print(f'[SKIP] {row["id"]}: {e}')
        continue

    batch.append({
        'id': row['id'],
        'ground_truth': row['ground_truth'],
        'y16': row['y16'],
        'y16_description': row['y16_description'],
        'image_mode': row['image_mode'],
        'describe_then_classify': predict_image(model, processor, image, prompt=PROMPT),
        'image_path': row['image_path'],
        'original_image_name': row['original_image_name'],
        'lesion_id': row['lesion_id'],
    })

    lesions_in_batch.add(row['lesion_id'])

    if len(lesions_in_batch) >= CHECKPOINT_EVERY:
        batch_df = pd.DataFrame(batch)[COL_ORDER]
        header = not os.path.exists(OUT_PATH)
        batch_df.to_csv(OUT_PATH, mode='a', header=header, index=False)
        print(f'\n[Checkpoint] +{len(batch)} rows ({len(lesions_in_batch)} lesions)')
        batch = []
        lesions_in_batch = set()

if batch:
    batch_df = pd.DataFrame(batch)[COL_ORDER]
    header = not os.path.exists(OUT_PATH)
    batch_df.to_csv(OUT_PATH, mode='a', header=header, index=False)
    print(f'\n[Final] +{len(batch)} rows ({len(lesions_in_batch)} lesions)')

print(f'\nAll predictions saved to {OUT_PATH}')

  0%|                                                                                     | 0/30 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
  3%|██▌                                                                          | 1/30 [00:51<24:59, 51.72s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
  7%|█████▏                                                                       | 2/30 [01:36<22:14, 47.67s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 10%|███████▋                                                                     | 3/30 [02:26<22:00, 48.90s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 13%|██████████▎                                                                  | 4/30 [03:13<20:49, 48.07s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 17%|████████████▊                                                                | 5/30 [03:57<19:23, 46.53s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 20%|███████████████▍                                                             | 6/30 [04:56<20:16, 50.70s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 23%|█████████████████▉                                                           | 7/30 [05:45<19:16, 50.26s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 27%|████████████████████▌                                                        | 8/30 [06:35<18:25, 50.23s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 30%|███████████████████████                                                      | 9/30 [07:29<17:56, 51.25s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 33%|█████████████████████████▎                                                  | 10/30 [08:22<17:17, 51.86s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 37%|███████████████████████████▊                                                | 11/30 [09:13<16:18, 51.50s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 40%|██████████████████████████████▍                                             | 12/30 [10:05<15:32, 51.79s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 43%|████████████████████████████████▉                                           | 13/30 [10:55<14:31, 51.26s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 47%|███████████████████████████████████▍                                        | 14/30 [11:41<13:15, 49.74s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 50%|██████████████████████████████████████                                      | 15/30 [12:30<12:22, 49.49s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 53%|████████████████████████████████████████▌                                   | 16/30 [13:19<11:30, 49.34s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 57%|███████████████████████████████████████████                                 | 17/30 [14:04<10:23, 47.96s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 60%|█████████████████████████████████████████████▌                              | 18/30 [14:59<09:59, 49.94s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 63%|████████████████████████████████████████████████▏                           | 19/30 [15:51<09:17, 50.64s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 67%|██████████████████████████████████████████████████▋                         | 20/30 [16:39<08:18, 49.86s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 70%|█████████████████████████████████████████████████████▏                      | 21/30 [17:32<07:36, 50.69s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 73%|███████████████████████████████████████████████████████▋                    | 22/30 [18:20<06:40, 50.10s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 77%|██████████████████████████████████████████████████████████▎                 | 23/30 [19:11<05:51, 50.24s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 80%|████████████████████████████████████████████████████████████▊               | 24/30 [20:06<05:09, 51.62s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 83%|███████████████████████████████████████████████████████████████▎            | 25/30 [20:52<04:10, 50.00s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 87%|█████████████████████████████████████████████████████████████████▊          | 26/30 [21:37<03:14, 48.58s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 90%|████████████████████████████████████████████████████████████████████▍       | 27/30 [22:34<02:33, 51.01s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 93%|██████████████████████████████████████████████████████████████████████▉     | 28/30 [23:29<01:44, 52.12s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
 97%|█████████████████████████████████████████████████████████████████████████▍  | 29/30 [24:11<00:49, 49.27s/it]Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:1 for open-end generation.
100%|████████████████████████████████████████████████████████████████████████████| 30/30 [25:06<00:00, 50.23s/it]

Collected 30 predictions

In [4]:
results_df = pd.read_csv(OUT_PATH)
print(f'Total predictions: {len(results_df)}')
print(f'Unique lesions:    {results_df["lesion_id"].nunique()}')
print(f'\nImage mode distribution:\n{results_df["image_mode"].value_counts()}')
print(f'\ny3 distribution:\n{results_df["ground_truth"].value_counts()}')
print(f'\ny16 distribution:\n{results_df["y16"].value_counts()}')
results_df.head(10)

Saved 30 rows to /scratch/jq2uw/derm_vlms/results/medgemma_predictions_paired.csv

,id,ground_truth,image_mode,describe,classify,describe_then_classify,original_image_name,lesion_id
0,1_photo,benign,photo,"Based on the image, here's a description of th...","Based on the image, here are the top 3 potenti...","Based on the image, here's a description of th...",s-prd-667118134.jpg,534_left lower leg_no
1,1_dscope,benign,dscope,"Based on the image, here's a description of th...","Based on the image, the top 3 differential dia...","Based on the image, here's a description of th...",s-prd-667118139.jpg,534_left lower leg_no
2,1_combined,benign,combined,"Based on the provided image, here's a descript...","Based on the image, the top 3 differential dia...","Based on the provided image, here's a descript...",s-prd-667118134.jpg; s-prd-667118139.jpg,534_left lower leg_no
3,2_photo,benign,photo,"Based on the image, here's a description of th...","Based on the image, here are the top 3 potenti...","Based on the image, here's a description of th...",s-prd-505211076.jpg,215_central chest _no
4,2_dscope,benign,dscope,"Based on the image, here's a description of th...","Based on the image, here are the top 3 differe...","Based on the image, here's a description of th...",s-prd-505211307.jpg,215_central chest _no
5,2_combined,benign,combined,"Based on the provided image, here's a descript...","Based on the image, the top 3 differential dia...","Based on the provided image, here's a descript...",s-prd-505211076.jpg; s-prd-505211307.jpg,215_central chest _no
6,3_photo,benign,photo,"Based on the image, here's a description of th...","Based on the image, the top 3 differential dia...","Based on the image, here's a description of th...",s-prd-529717709.jpg,262_left buttock_no
7,3_dscope,benign,dscope,"Based on the image, here's a description of th...","Based on the image, the top 3 differential dia...","Based on the image, here's a description of th...",s-prd-529718156.jpg,262_left buttock_no
8,3_combined,benign,combined,"Based on the provided images, here's a descrip...","Based on the image, the top 3 differential dia...","Based on the provided images, here's a descrip...",s-prd-529717709.jpg; s-prd-529718156.jpg,262_left buttock_no
9,4_photo,benign,photo,"Based on the image, here's a description of th...","Based on the image, the top 3 differential dia...","Based on the image, here's a description of th...",s-prd-649658541.jpg,476_mid vertex_no
10,4_dscope,benign,dscope,"Based on the image, here's a description of th...","Based on the image, the top 3 differential dia...","Based on the image, here's a description of th...",s-prd-649659064.jpg,476_mid vertex_no
11,4_combined,benign,combined,"Based on the provided images, here is a descri...","Based on the image, the top 3 differential dia...","Based on the provided image, here is a descrip...",s-prd-649658541.jpg; s-prd-649659064.jpg,476_mid vertex_no
12,5_photo,benign,photo,"Based on the image, here's a description of th...","Based on the image, here are the top 3 potenti...","Based on the image, here's a description of th...",s-prd-697813991.jpg,604_l forehead_no
13,5_dscope,benign,dscope,"Based on the image, here's a description of th...","Based on the image, here are the top 3 differe...","Based on the image, here's a description of th...",s-prd-697814488.jpg,604_l forehead_no
14,5_combined,benign,combined,"Based on the provided images, here's a descrip...","Based on the image, here are the top 3 differe...","Based on the provided image, here's a descript...",s-prd-697813991.jpg; s-prd-697814488.jpg,604_l forehead_no
15,6_photo,malignant,photo,"Based on the image, here's a description of th...","Based on the image, the top 3 differential dia...","Based on the image, here's a description of th...",s-prd-610265816.jpg,384_r vertex scalp_no
16,6_dscope,malignant,dscope,"Based on the image, here's a description of th...","Based on the image, the top 3 differential dia...","Based on the image, here's a description of th...",s-prd-610268327.jpg,384_r vertex scalp_no
17,6_combined,malignant,combined,"Based on the provided image, here's a descript...","Based on the image, the top 3 differential dia...","Based on the provided image, here is a descrip...",s-prd-610265816.jpg; s-prd-610268327.jpg,384_r vertex scalp_no
18,7_photo,malignant,photo,"Based on the image, here's a description of th...","Based on the image, here are the top 3 potenti...","Based on the image, here's a description of th...",s-prd-472171238.jpg,131_r dorsal hand_no
19,7_dscope,malignant,dscope,"Based on the image, here's a description of th...","Based on the image, here are the top 3 differe...","Based on the image, here's a description of th...",s-prd-472171643.jpg,131_r dorsal hand_no
20,7_combined,malignant,combined,"Based on the provided image, here's a descript...","Based on the image, here are the top 3 differe...","Based on the provided image, here's a descript...",s-prd-472171238.jpg; s-prd-472171643.jpg,131_r dorsal hand_no
21,8_photo,malignant,photo,"Based on the image, here's a description of th...","Based on the image, here are the top 3 differe...","Based on the image, here's a description of th...",s-prd-421710389.jpg,13_l proximal dorsal forearm _no
22,8_dscope,malignant,dscope,"Based on the image, here's a description of th...","Based on the image, here are the top 3 differe...","Based on the image, here's a description of th...",s-prd-421709013.jpg,13_l proximal dorsal forearm _no
23,8_combined,malignant,combined,"Based on the provided image, here's a descript...","Based on the image, the top 3 differential dia...","Based on the provided image, here's a descript...",s-prd-421710389.jpg; s-prd-421709013.jpg,13_l proximal dorsal forearm _no
24,9_photo,malignant,photo,"Based on the image, here's a description of th...","Based on the image, the top 3 differential dia...","Based on the image, here's a description of th...",s-prd-608746040.jpg,380_left neck_no
25,9_dscope,malignant,dscope,"Based on the image, here's a description of th...","Based on the image, here are the top 3 differe...","Based on the image, here's a description of th...",s-prd-608746848.jpg,380_left neck_no
26,9_combined,malignant,combined,"Based on the provided image, here's a descript...","Based on the image, the top 3 differential dia...","Based on the provided image, here's a descript...",s-prd-608746040.jpg; s-prd-608746848.jpg,380_left neck_no
27,10_photo,malignant,photo,"Based on the image, here's a description of th...","Based on the image, here are the top 3 potenti...","Based on the image, here's a description of th...",s-prd-509613419.jpg,225_right elbow _no
28,10_dscope,malignant,dscope,"Based on the image, here's a description of th...","Based on the image, here are the top 3 differe...","Based on the image, here's a description of th...",s-prd-509613622.jpg,225_right elbow _no
29,10_combined,malignant,combined,"Based on the provided image, here's a descript...","Based on the image, here are the top 3 differe...","Based on the provided image, here's a descript...",s-prd-509613419.jpg; s-prd-509613622.jpg,225_right elbow _no